---
title: "Mad Fermentiationist's Red Rye IPA"
output: github_document
---


Original recipe from [here](https://www.themadfermentationist.com/2012/08/india-red-rye-ale-recipe.html) and [here](https://www.themadfermentationist.com/2013/04/three-modern-times-west-test-batches.html), [mine](https://www.brewersfriend.com/homebrew/recipe/view/672949/madfermentationist-s-red-rye-ipa)

```{r setup-variables, echo=FALSE}

brewlog_file = '../recipes/red rye ipa/brewlog_2018-07-05.xml'

```

```{r test-include, child = '../../scripts/brewlog-template.Rmd'}
```


Preparation Notes
=================

* https://www.morebeer.com/articles/treating_homebrew_water
* Target Water Profile: 150ppm of sulfate and 150ppm of chloride
* Water Additions:
    * 1.5g Gypsum
    * 5.71 Calcium Chloride (4.4g, but since it's 77%, 5.71g)
    * 4.9g Epsom Salt
    * 3.0ml Lactic Acid (80%)
* Adjusted Water Profile:
    * Calcium: 152ppm
    * Magnesium: 30ppm
    * Sodium: 3ppm
    * Sulfate: 152ppm
    * Chloride: 151ppm
    * Bicarbonate: 66ppm
    

