---
title: "Mad Fermentiationist's India Red Ale"
output: github_document
---


[original recipe](https://www.themadfermentationist.com/2011/04/india-red-ale-recipe.html), [mine](https://www.brewersfriend.com/homebrew/recipe/view/899493/mad-fermentationist-s-india-red-ale)

```{r setup-variables, echo=FALSE}

boiloff_rate_override = 4.0
brewlog_file = '../recipes/india red ale/brewlog.xml'

```

```{r test-include, child = '../../scripts/brewlog-template.Rmd'}
```

Water Information
=================

* Target Water Profile:
    * Sodium: 50ppm
    * Sulfate: 150ppm
    * Chloride: 150ppm
    * Mash pH: 5.30
* Water Additions:
    * 2.2g Gypsum
    * 4.4g Calcium Chloride (3.4g, but since it's 77%, 4.4g)
    * 7.3g Epsom Salt
    * 5.9ml Lactic Acid (80%)
    * 3.4g Salt
* Adjusted Water Profile:
    * Calcium: 113ppm
    * Magnesium: 30ppm
    * Sodium: 50ppm
    * Sulfate: 152ppm
    * Chloride: 155ppm
    * Bicarbonate: 66ppm
    * Estimated Mash pH: 5.30

# Preparation Notes

# Notes

# Bottling Notes

